version: 0.2

phases:
  build:
    commands:
      - echo "No build commands needed for a static HTML site."
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**/*